---
title: "Prediction Intervals in Series Systems with Masked Failure Causes"
author: "Alex Towell"
abstract: "..."
output:
    #bookdown::html_document2:
    #bookdown::pdf_document2:
    bookdown::gitbook:
        df_print: kable
        citation_package: natbib
    bookdown::pdf_book:
        toc: true
        #toc_depth: 3
        number_sections: true
        #extra_dependencies: ["hyperref", "graphicx","amsthm","amsmath","natbib","tikz"]
        extra_dependencies: ["tikz", "caption"]
        df_print: kable
        #keep_tex: true
        citation_package: natbib
indent: true
header-includes:
   - \usepackage{tikz}
   - \usepackage{caption}
   - \AtBeginDocument{\renewcommand{\v}[1]{\boldsymbol{#1}}}
   - \AtBeginDocument{\newtheorem{condition}{Condition}}
bibliography: refs.bib
link-citations: true
biblio-style: apalike
---



# Probability of Component Cause of System Failure {#app-prob-k-given-t-and-c}
This subsection is not necessary in our likelihood model, but it derives a useful
result for making predictions about the component cause of failure.
Suppose we have observed a candidate set and a series system
failure and we are interested in the probability that a particular component
is the cause of failure.
::: {.theorem}
Assuming Conditions \ref{cond:c_contains_k} and \ref{cond:equal_prob_failure_cause},
the conditional probability of the component cause of failure is component $j$ ($K_i = j$)
given a masked component cause of failure ($\mathcal{C}_i = c_i$) and system lifetime ($T_i = t_i$)
is given by
\begin{equation}
\label{eq:cond_prob_k_given_t_and_c}
\Pr\{K_i = j|T_i=t_i,\mathcal{C}_i=c_i\} =
 \frac{h_j(t_i;\v{\theta_j})}{\sum_{l \in c_i} h_l(t_i;\v{\theta_l})} 1_{\{j \in c_i\}}.
\end{equation}
:::

::: {.proof}
The conditional probability $\Pr\{K_i = j|T_i=t_i,\mathcal{C}_i=c_i\}$ may be
written as
$$
\Pr\{K_i = j|T_i=t_i,\mathcal{C}_i=c_i\} =
    \frac{\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} f_{K_i,T_i}(j,t_i;\v\theta)}
    {\sum_{j=1}^m \Pr{}_{\!\v\theta}
        \{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} f_{K_i,T_i}(j,t_i;\v\theta)}.
$$
By Theorem \@ref(thm:f-k-and-t), we know that
$f_{K_i,T_i}(j,t_i;\v\theta) = h_j(t_i;\v\theta)R_{T_i}(t_i;\v\theta)$.
We may make this substitution and simplify:
$$
\Pr\{K_i = j|T_i=t_i,\mathcal{C}_i=c_i\} =
    \frac{\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} h_j(t_i;\v{\theta_j})}
         {\sum_{j'=1}^m \Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i=j',T_i=t_i\} h_{j'}(t_i;\v{\theta_{j'}})}.
$$
Assuming Conditions \ref{cond:c_contains_k} and \ref{cond:equal_prob_failure_cause}, we may rewrite the above
as
$$
\Pr\{K_i = j|T_i=t_i,\mathcal{C}_i=c_i\} =
    \frac{\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} h_j(t_i;\v{\theta_j})}
    {\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} {\sum_{l \in c_i} h_l(t_i;\v{\theta_l})}} =
    \frac{h_j(t_i;\v{\theta_j})}
    {\sum_{l \in c_i} h_l(t_i;\v{\theta_l})}.
$$
:::
