---
title: "Component Cause of Failure in a Series System with Masked Component Cause of Failure"
author: "Alex Towell"
output:
    pdf_document:
        toc: yes
        toc_depth: 2
        number_sections: true
        extra_dependencies: ["hyperref", "graphicx","amsthm","amsmath","natbib","tikz"]
        df_print: kable
        keep_tex: true
        citation_package: natbib
indent: true
header-includes:
   - \hypersetup{linktoc=all}
   - \AtBeginDocument{\renewcommand{\refname}{References}}
bibliography: refs.bib
biblio-style: apalike
#csl: the-annals-of-statistics.csl
---

\newcommand{\T}{T}
\newtheorem{definition}{Definition}
\newtheorem{theorem}{Theorem}
\newtheorem{corollary}{Corollary}
\newtheorem{condition}{Condition}
\renewcommand{\v}[1]{\boldsymbol{#1}}
\numberwithin{equation}{section}

## Probability of Component Cause of System Failure

This subsection is not necessary in our likelihood model, but it derives a useful
result for making predictions about the component cause of failure.

Suppose we have observed a candidate set and a series system
failure and we are interested in the probability that a particular component
is the cause of failure.
\begin{theorem}
Assuming Conditions \ref{cond:c_contains_k} and \ref{cond:equal_prob_failure_cause},
the conditional probability of the component cause of failure is component $j$ ($K_i = j$) given a masked component cause of failure ($\mathcal{C}_i = c_i$) and system lifetime ($\T_i = t_i$)
is given by
\begin{equation}
\label{eq:cond_prob_k_given_t_and_c}
\Pr\{K_i = j|\T_i=t_i,\mathcal{C}_i=c_i\} =
 \frac{h_j(t_i|\v{\theta_j})}{\sum_{l \in c_i} h_l(t_i|\v{\theta_l})} 1_{\{j \in c_i\}}.
\end{equation}
\end{theorem}
\begin{proof}
The conditional probability $\Pr\{K_i = j|\T_i=t_i,\mathcal{C}_i=c_i\}$ may be
written as
$$
\Pr\{K_i = j|\T_i=t_i,\mathcal{C}_i=c_i\} =
    \frac{\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} f_{K_i,\T_i}(j,t_i;\v\theta)}
    {\sum_{j=1}^m \Pr{}_{\!\v\theta}
        \{\mathcal{C}_i=c_i|K_i = j,\T_i=t_i\} f_{K_i,\T_i}(j,t_i;\v\theta)}.
$$
By Theorem \ref{thm:f_k_and_t},
$f_{K_i,T_i}(j,t_i;\v\theta) = h_j(t_i;\v\theta)R_{\T_i}(t_i;\v\theta)$.
We may make this substitution and simplify:
$$
\Pr\{K_i = j|\T_i=t_i,\mathcal{C}_i=c_i\} =
    \frac{\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} h_j(t_i;\v{\theta_j})}
         {\sum_{j'=1}^m \Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i=j',\T_i=t_i\} h_{j'}(t_i;\v{\theta_{j'}})}.
$$
Assuming Conditions \ref{cond:c_contains_k} and \ref{cond:equal_prob_failure_cause}, we may rewrite the above
as
$$
\Pr\{K_i = j|T_i=t_i,\mathcal{C}_i=c_i\} =
    \frac{\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} h_j(t_i;\v{\theta_j})}
    {\Pr{}_{\!\v\theta}\{\mathcal{C}_i=c_i|K_i = j,T_i=t_i\} {\sum_{l \in c_i} h_l(t_i;\v{\theta_l})}} =
    \frac{h_j(t_i;\v{\theta_j})}
    {\sum_{l \in c_i} h_l(t_i;\v{\theta_l})}.
$$
\end{proof}

Frequently, we may not have any information at all about the component cause of
failure. In this case, $c_i = \{1,\ldots,m\}$, and we obtain the following corollary.
\begin{corollary}
The probability that the $j$\textsuperscript{th}
component is the cause of system failure given only that we know a system failure
occured at time $t_i$ is given by
$$
\Pr\{K_i = j|T_i=t_i\} = \frac{h_j(t_i;\v{\theta_j})}{\sum_{l=1}^m h_l(t_i;\v{\theta_l})}.
$$
\end{corollary}
